tons of functionality
baking-bad/matrix-dotnet-sdk pull request #11
Opened 2023-05-08 07:55 UTC by SlimeQ

I've been fleshing out this library for a personal project for a few months and at this point I've added a fairly long list of functionality:

- Pulling history
- Making edits
- Sending typing signals
- Uploading images
- Downloading images

The following message types now parse properly:
- EditEvent
- ImageMessageEvent
- RedactionEvent
- ReactionEvent

2023-05-08 13:25 UTC, m-kus commented
Hey! This is amazing, thank you so much for the PR!
We will also test it in our workflow to make sure everything works as expected

2023-05-08 17:32 UTC, SlimeQ commented
:pray: 

https://github.com/baking-bad/matrix-dotnet-sdk/pull/11/files#diff-8217a0e68eb87c2a384ccdd80065834abfcad13f507adb70e6357e4fe83270e6

This spot in particular should probably be massaged a bit. I wasn't sure at the time how to get a reference to the event factory, so I made a static one. Personally I would go with a static class to house those factory functions, if this were my own project, but idk if there are any unforseen implications to keeping that in the static context.

2023-05-09 10:45 UTC, SlimeQ commented
I just went through and cleaned everything up and made it run. Downgraded the syntax to C# 9

Among some minor housekeeping changes:

- JoinedRoom/LeftRoom are now simply RoomResponse objects. These classes were identical and having both of them meant that code had to be copied twice in several places.
- I got rid of the MatrixRoom/RoomEvent factories; they did not seem to have any reason not to be static, and caused a ton of confusion when I was initially digging through this. Now those functions are static and contained by the object they are intended to create.
- MarkDig is now a dependency; this was in last night but not set up properly in the PR. I'm using this to generate the formatted_body on outgoing messages.


I cannot actually test this properly, as dotnet 5 is no longer supported on linux. However it does actually compile now.

2024-02-13 19:54 UTC, DevTown commented
Will this PR be merged soon or is this project dead ?

2024-02-13 20:22 UTC, SlimeQ commented
> Will this PR be merged soon or is this project dead ?

No idea, feel free to use my fork. I technically have some more stuff now around membership events that I haven't merged yet

2024-02-15 15:36 UTC, k-karuna commented
Hi @DevTown @SlimeQ 
Sorry for long response, i will check out and test for bugs @SlimeQ changes in the coming days and merge them if everything well.

2024-02-26 17:34 UTC, k-karuna requested changes
@SlimeQ
`Matrix.Sdk/MatrixClientServiceExtensions.cs` should contain adding `services.AddSingleton<MediaService>();` otherwise it will not work in case of DependencyInjection builder.

Also please update Newtonsoft to 13.0.3

2024-02-26 17:34 UTC, k-karuna commented on Matrix.Sdk/Matrix.Sdk.csproj
Please update Newtonsoft to 13.0.3

2024-03-13 19:45 UTC, merged